# Generated by Django 2.0 on 2018-02-09 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcomment', models.TextField()),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='comment.Comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('subcomment', 'upvote', 'downvote', 'created', 'owner'),
            },
        ),
    ]
